# Coherent info

In [1]:
import numpy as np
from collections import Counter
from typing import Tuple, Iterable, Dict, List
from coherentinfo.moebius import (build_moebius_code_vertex,
                                  index_h, index_v, inverted_index_h)
from coherentinfo.linalg import finite_field_gauss_jordan_elimination
from functools import partial

In [ ]:
# -------------------------------
# Möbius/cylinder strip (d=2)
# -------------------------------
def build_mobius_code_old(L: int, w: int) -> Tuple[np.ndarray, np.ndarray, int]:
    assert L >= 2 and w >= 2

    nH = L * (w - 1)  # horizontal edges
    nV = L * w  # vertical edges
    n = nH + nV

    def idxH(y, x):
        return y * L + (x % L)

    def idxV(y, x):
        return nH + y * L + (x % L)

    # Z-check matrix
    rows = []
    for y in range(w - 1):
        for x in range(L):
            row = np.zeros(n, dtype=np.uint8)
            row[idxH(y, x)] ^= 1
            row[idxH(y, x - 1)] ^= 1
            row[idxV(y, x)] ^= 1
            row[idxV(y + 1, x)] ^= 1
            rows.append(row)
    H_Z = np.array(rows, dtype=np.uint8)

    # Logical Z along vertical edges in second row
    l_Z = np.zeros(n, dtype=np.uint8)
    y0 = w//2
    for x in range(L):
        l_Z[idxV(y0, x)] = 1

    return H_Z, l_Z

In [24]:
pippo = np.zeros([2, 2], dtype=np.uint8)
pippo[0, [0, 1]] = [1, 3]
print(pippo)

[[1 3]
 [0 0]]


In [18]:
width = 3
length = 5

h_z, l_z = build_moebius_code_vertex(1, 1)

AssertionError: 

In [20]:
print(h_z)

[[1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]]


In [7]:
pippo, pluto = h_z.shape

In [8]:
pippo

15

In [9]:
pluto

35

In [18]:
a

0