# Coherent info

In [1]:
import numpy as np
from collections import Counter
from typing import Tuple, Iterable, Dict, List
from coherentinfo.moebius import MoebiusCode
from coherentinfo.linalg import (finite_field_gauss_jordan_elimination,
                                 finite_field_matrix_rank,
                                 finite_field_inverse,
                                 is_prime)
# import galois
import timeit

In [2]:
length = 7
width = 9
p = 7
moebius_code = MoebiusCode(length=length, width=width, d=2 * p)
h_z = moebius_code.h_z
h_x = moebius_code.h_x
logical_x = moebius_code.logical_x
logical_z = moebius_code.logical_z

In [6]:
moebius_code.h_x_mod_p
destab_h_x_mod_p = moebius_code.build_plaquette_destabilizers_mod_p()
id_mat = np.identity(h_x.shape[0])
print(np.count_nonzero((moebius_code.h_x_mod_p @ destab_h_x_mod_p.T - id_mat) % p))

0


In [4]:
mat = h_x % p

In [5]:
mat.shape

(63, 119)

In [8]:
finite_field_matrix_rank(mat @ mat.T, p)

61

In [3]:
destab_h_x_qupit = moebius_code.build_plaquette_destabilizers_qupit()
print(destab_h_x_qupit)

AttributeError: 'MoebiusCode' object has no attribute 'build_plaquette_destabilizers_qupit'

In [11]:
h_x @ destab_h_x_qupit.T % p

AttributeError: 'NoneType' object has no attribute 'T'

In [38]:
destab_type_2 = moebius_code.build_plaquette_destabilizers_type_two()

In fact, we can also explicitly check that

In [39]:
print((2 * h_x) @  (2 * pre_destab_h_x.T) % (2 * p))

[[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 4 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 4]]


In [40]:
logical_x @ (2 * pre_destab_h_x.T) % (2 * p)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Surface code

In [ ]:
h_x_surface = np.zeros([4, 9], dtype=np.int_)

h_x_surface[0, 0] = 1
h_x_surface[0, 1] = 1
h_x_surface[0, 3] = 1
h_x_surface[0, 4] = 1

h_x_surface[1, 1] = 1
h_x_surface[1, 2] = 1

h_x_surface[2, 4] = 1
h_x_surface[2, 5] = 1
h_x_surface[2, 7] = 1
h_x_surface[2, 8] = 1

h_x_surface[3, 6] = 1
h_x_surface[3, 7] = 1

In [6]:
finite_field_matrix_rank(h_x_surface, 2)

4

In [7]:
finite_field_gauss_jordan_elimination(h_x_surface, 2)

array([[1, 0, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0]])

In [8]:
gf = galois.GF(2)

h_x_surface_galois = gf(h_x_surface)

In [9]:
h_x_surface_galois.row_reduce()

GF([[1, 0, 1, 1, 0, 1, 0, 1, 1],
    [0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 1, 1, 0]], order=2)

In [41]:
for row in reversed(range(2)):
    print(row)

1
0


In [43]:
x = 2
x -= 1
print(x)

1


# Shobhna matrix

In [ ]:
h_x_test = np.zeros([moebius_code.num_plaquette_checks,
                    moebius_code.num_edges], dtype=np.int_)

# Stab 0
h_x_test[0, 0] = -1
h_x_test[0, 6] = 1
h_x_test[0, 7] = 1

# Stab 1
h_x_test[1, 1] = 1
h_x_test[1, 7] = -1
h_x_test[1, 8] = -1

# Stab 2
h_x_test[2, 2] = -1
h_x_test[2, 8] = 1
h_x_test[2, 12] = 1

# Stab 3
h_x_test[3, 0] = 1
h_x_test[3, 3] = 1
h_x_test[3, 9] = -1
h_x_test[3, 10] = -1

# Stab 4
h_x_test[4, 1] = -1
h_x_test[4, 4] = -1
h_x_test[4, 10] = 1
h_x_test[4, 11] = 1

# Stab 5
h_x_test[5, 2] = 1
h_x_test[5, 5] = 1
h_x_test[5, 9] = -1
h_x_test[5, 11] = -1

# Stab 6
h_x_test[6, 3] = -1
h_x_test[6, 12] = 1
h_x_test[6, 13] = 1

# Stab 7
h_x_test[7, 4] = 1
h_x_test[7, 13] = -1
h_x_test[7, 14] = -1

# Stab 7
h_x_test[8, 5] = -1
h_x_test[8, 6] = 1
h_x_test[8, 14] = 1

In [8]:
# We check the rank
finite_field_matrix_rank(h_x_test % p, p)

9

In [ ]:
destab_x_test = np.zeros(
    [moebius_code.num_plaquette_checks, moebius_code.num_edges], dtype=np.int_)

# Destab 0
destab_x_test[0, 0] = -1
destab_x_test[0, 2] = 1
destab_x_test[0, 3] = 1
destab_x_test[0, 5] = 1
destab_x_test[0, 6] = -1
destab_x_test[0, 12] = 1

# Destab 1
destab_x_test[1, 0] = -1
destab_x_test[1, 1] = 1
destab_x_test[1, 3] = 1
destab_x_test[1, 4] = -1
destab_x_test[1, 8] = 1
destab_x_test[1, 12] = 1
destab_x_test[1, 14] = -1

# Destab 2
destab_x_test[2, 0] = -1
destab_x_test[2, 2] = -1
destab_x_test[2, 3] = 1
destab_x_test[2, 5] = 1
destab_x_test[2, 6] = -1
destab_x_test[2, 12] = 1

# Destab 3
destab_x_test[3, 0] = 1
destab_x_test[3, 3] = 1
destab_x_test[3, 9] = -1
destab_x_test[3, 10] = -1

# Destab 4
destab_x_test[4, 1] = -1
destab_x_test[4, 3] = -1
destab_x_test[4, 8] = -1
destab_x_test[4, 9] = -1
destab_x_test[4, 11] = -1
destab_x_test[4, 12] = -1

# Destab 5
destab_x_test[5, 2] = -1
destab_x_test[5, 3] = -1
destab_x_test[5, 9] = -1
destab_x_test[5, 12] = -1

# Destab 6
destab_x_test[6, 0] = 1
destab_x_test[6, 2] = 1
destab_x_test[6, 3] = -1
destab_x_test[6, 5] = -1
destab_x_test[6, 6] = 1
destab_x_test[6, 12] = -1

# Destab 7
destab_x_test[7, 0] = 1
destab_x_test[7, 1] = -1
destab_x_test[7, 3] = -1
destab_x_test[7, 4] = 1
destab_x_test[7, 6] = 1
destab_x_test[7, 8] = -1
destab_x_test[7, 12] = -1
destab_x_test[7, 14] = 1

# Destab 8
destab_x_test[8, 0] = 1
destab_x_test[8, 2] = 1
destab_x_test[8, 3] = -1
destab_x_test[8, 5] = -1
destab_x_test[8, 6] = 1
destab_x_test[8, 12] = -1

In [10]:
h_x_test @ destab_x_test.T % (2 * p)

array([[0, 1, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 0, 4, 0, 4, 4, 4],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 0],
       [2, 0, 0, 1, 2, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 5, 4, 0, 0, 0, 2, 2, 2]])

In [14]:
finite_field_matrix_rank(destab_x_test, p)

7

In [37]:
h_x_test[0, 7]

np.int64(1)

In [ ]:
destab_x_test[, :]

array([-1,  1,  0,  1, -1,  0,  0,  0,  1,  0,  0,  0,  1,  0, -1])