# Coherent info

In [2]:
import numpy as np
from collections import Counter
from typing import Tuple, Iterable, Dict, List
from coherentinfo.moebius import (MoebiusCode)
from coherentinfo.linalg import finite_field_gauss_jordan_elimination
from functools import partial

In [2]:
# -------------------------------
# Möbius/cylinder strip (d=2)
# -------------------------------
def build_mobius_code_old(L: int, w: int) -> Tuple[np.ndarray, np.ndarray, int]:
    assert L >= 2 and w >= 2

    nH = L * (w - 1)  # horizontal edges
    nV = L * w  # vertical edges
    n = nH + nV

    def idxH(y, x):
        return y * L + (x % L)

    def idxV(y, x):
        return nH + y * L + (x % L)

    # Z-check matrix
    rows = []
    for y in range(w - 1):
        for x in range(L):
            row = np.zeros(n, dtype=np.uint8)
            row[idxH(y, x)] ^= 1
            row[idxH(y, x - 1)] ^= 1
            row[idxV(y, x)] ^= 1
            row[idxV(y + 1, x)] ^= 1
            rows.append(row)
    H_Z = np.array(rows, dtype=np.uint8)

    # Logical Z along vertical edges in second row
    l_Z = np.zeros(n, dtype=np.uint8)
    y0 = w//2
    for x in range(L):
        l_Z[idxV(y0, x)] = 1

    return H_Z, l_Z

In [ ]:
pippo = MoebiusCode(length=5, width=3, d=2)
expected_h_z = np.zeros([10, 25], dtype=np.int8)
expected_h_z[0, [0, 9, 10, 15]] = 1
expected_h_z[1, [0, 1, 11, 16]] = -1
expected_h_z[2, [1, 2, 12, 17]] = 1
expected_h_z[3, [2, 3, 13, 18]] = -1
expected_h_z[4, [3, 4, 14, 19]] = 1
expected_h_z[5, [5, 4, 15, 20]] = -1
expected_h_z[6, [5, 6, 16, 21]] = 1
expected_h_z[7, [6, 7, 17, 22]] = -1
expected_h_z[8, [7, 8, 18, 23]] = 1
expected_h_z[9, [8, 9, 19, 24]] = -1
print(pippo.h_z - expected_h_z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [18]:
width = 3
length = 5

h_z, l_z = build_moebius_code_vertex(1, 1)

AssertionError: 

In [20]:
print(h_z)

[[1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]]


In [7]:
pippo, pluto = h_z.shape

In [8]:
pippo

15

In [9]:
pluto

35

In [18]:
a

0